---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Vhost configuration.
#- import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx service is running as configured.
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"

- name: Remove the default site
  shell: rm -r /etc/nginx/sites-enabled/default  

- name: Copy file with owner and permissions
  copy:
    src: /home/gib/horbatko-homework/ansible/roles/geerlingguy.nginx/files/www
    dest: /etc/nginx/sites-enabled/www
    owner: www-data
    group: www-data
    mode: '0644'

- name: Nginx Restart
  shell: /etc/init.d/nginx restart
 
