##Docker branche
FROM alpine

RUN apk update --no-cache
RUN apk add git
 
ENV giturl=https://github.com/svgib/horbatko-homework.git

RUN mkdir /data
WORKDIR /data
VOLUME /data

CMD git clone $giturl

